name: Static Security Analysis

on:
  push:
    branches:
      - main

jobs:
  checkov:
    name: Run Checkov
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run Checkov
        run: docker run -v $PWD:/tf bridgecrew/checkov --directory /tf
